CREATE TABLE IF NOT EXISTS dim_user (
    user_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(100) UNIQUE NOT NULL,
    first_seen_date_key BIGINT REFERENCES dim_date(date_key),
    acquisition_channel VARCHAR(100),
    user_type VARCHAR(20) DEFAULT 'new',
    lifetime_orders INTEGER DEFAULT 0,
    lifetime_revenue NUMERIC(15, 2) DEFAULT 0.00
);

CREATE INDEX IF NOT EXISTS idx_dim_user_first_seen_date_key ON dim_user(first_seen_date_key);
