CREATE TABLE IF NOT EXISTS dim_channel (
    channel_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    traffic_source VARCHAR(100) NOT NULL,
    campaign VARCHAR(100) NOT NULL,
    channel_group VARCHAR(100),
    CONSTRAINT uq_traffic_source_campaign UNIQUE (traffic_source, campaign)
);
