CREATE TABLE IF NOT EXISTS dim_device (
    device_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device VARCHAR(50) NOT NULL,
    browser VARCHAR(50) NOT NULL,
    os_family VARCHAR(50),
    is_mobile BOOLEAN,
    CONSTRAINT uq_device_browser UNIQUE (device, browser)
);
