CREATE TABLE IF NOT EXISTS dim_product (
    product_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(100) UNIQUE NOT NULL,
    product_name VARCHAR(255),
    category VARCHAR(100),
    sub_category VARCHAR(100),
    unit_price NUMERIC(15, 2)
);

CREATE INDEX IF NOT EXISTS idx_dim_product_category ON dim_product(category);
