CREATE TABLE IF NOT EXISTS dim_location (
    location_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    region VARCHAR(100),
    tier VARCHAR(20),
    CONSTRAINT uq_city_country UNIQUE (city, country)
);
