CREATE TABLE IF NOT EXISTS etl_watermark (
    table_name VARCHAR(50) PRIMARY KEY,
    last_loaded_ts TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS etl_run_log (
    run_id VARCHAR(50) PRIMARY KEY,
    source_file VARCHAR(255),
    file_hash VARCHAR(64),
    rows_in INT,
    rows_loaded INT,
    rows_quarantined INT,
    status VARCHAR(20),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    error_message TEXT
);

CREATE TABLE IF NOT EXISTS quarantine_events (
    quarantine_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(50),
    raw_data JSONB,
    failed_rule VARCHAR(100),
    quarantined_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
